[package]
name = "date-calc-rs"
version = "0.2.0"
edition = "2021"
authors = ["Oliver <oliver.d.333@proton.me"]
description = "Given a number of days, calculates the date from today"
license = "MIT"

[dependencies]
chrono = "0.4.38"
clap = "4.5.20"
